apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prom-monitoring
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prom-monitoring
  template:
    metadata:
      labels:
        app: prom-monitoring
    spec:
      containers:
        - name: prom-monitoring-container
          image: prom/prom-monitoring/latest
          ports:
            - containerPort: 9100
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
              