version: '3'

services:
  app:
    build: .
    container_name: python-prom-app
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml

    ports:
      - "9090:9090"
    
  elk:
    image: elasticsearch:9.0.1
    container_name: hopeful_cohen_2
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Logstash pipeline config
    ports:
      - "5044:5044"  # Port for Filebeat or other log sources to send logs
    depends_on:
      - elk  # Ensure Elasticsearch is running before Logstash
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://elk:9200  # Point Logstash to Elasticsearch

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"  # Expose Kibana on port 5601
    depends_on:
      - elk  # Ensure Elasticsearch is running before Kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elk:9200  # Point Kibana to Elasticsearch